import type { StateRequirement } from "@/lib/classmap/types";
import { SUBJECTS } from "@/lib/classmap/types";

const STUB_NOTE =
  "Compliance summary forthcoming — consult HSLDA or your state's homeschool organization for current requirements.";

export const STATE_REQUIREMENTS: StateRequirement[] = [
  {
    code: "AK",
    name: "Alaska",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "AL",
    name: "Alabama",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "AR",
    name: "Arkansas",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "AZ",
    name: "Arizona",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "CA",
    name: "California",
    hoursPerYear: null,
    subjectsRequired: [
      "math",
      "reading",
      "writing",
      "science",
      "history",
      "art",
      "music",
      "physical-education",
    ],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: true,
    notes:
      "File a private-school affidavit annually if homeschooling independently, or enroll through a Private School Satellite Program (PSP) or charter.",
  },
  {
    code: "CO",
    name: "Colorado",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "CT",
    name: "Connecticut",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "DE",
    name: "Delaware",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "FL",
    name: "Florida",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: true,
    testingRequired: false,
    notificationOfIntent: true,
    notes:
      "Notify the district superintendent, maintain a portfolio, and submit an annual evaluation.",
  },
  {
    code: "GA",
    name: "Georgia",
    hoursPerYear: 810,
    subjectsRequired: ["math", "reading", "writing", "science", "history"],
    portfolioRequired: true,
    testingRequired: true,
    notificationOfIntent: true,
    notes:
      "Submit a declaration of intent annually; keep attendance, monthly reports, and a triennial standardized test.",
  },
  {
    code: "HI",
    name: "Hawaii",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "IA",
    name: "Iowa",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "ID",
    name: "Idaho",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "IL",
    name: "Illinois",
    hoursPerYear: null,
    subjectsRequired: [
      "math",
      "reading",
      "writing",
      "science",
      "history",
      "art",
      "music",
      "physical-education",
      "life-skills",
    ],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes:
      "Operate as a private school; cover the listed subjects; no notice or testing required.",
  },
  {
    code: "IN",
    name: "Indiana",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "KS",
    name: "Kansas",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "KY",
    name: "Kentucky",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "LA",
    name: "Louisiana",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "MA",
    name: "Massachusetts",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "MD",
    name: "Maryland",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "ME",
    name: "Maine",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "MI",
    name: "Michigan",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "MN",
    name: "Minnesota",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "MO",
    name: "Missouri",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "MS",
    name: "Mississippi",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "MT",
    name: "Montana",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "NC",
    name: "North Carolina",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: true,
    notificationOfIntent: true,
    notes:
      "File a notice of intent with NCDNPE, keep attendance and immunization records, administer an annual nationally standardized test.",
  },
  {
    code: "ND",
    name: "North Dakota",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "NE",
    name: "Nebraska",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "NH",
    name: "New Hampshire",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "NJ",
    name: "New Jersey",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "NM",
    name: "New Mexico",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "NV",
    name: "Nevada",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "NY",
    name: "New York",
    hoursPerYear: 900,
    subjectsRequired: [
      "math",
      "reading",
      "writing",
      "science",
      "history",
      "geography",
      "art",
      "music",
      "physical-education",
      "foreign-language",
    ],
    portfolioRequired: true,
    testingRequired: true,
    notificationOfIntent: true,
    notes:
      "Submit an Individualized Home Instruction Plan (IHIP) by July 1, file quarterly reports, and an annual assessment. Grades K–6 require 900 hours/year; grades 7–12 require 990 hours/year.",
  },
  {
    code: "OH",
    name: "Ohio",
    hoursPerYear: 900,
    subjectsRequired: [
      "math",
      "reading",
      "writing",
      "science",
      "history",
      "geography",
      "art",
      "music",
      "physical-education",
      "life-skills",
    ],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: true,
    notes:
      "Notify the district superintendent annually and submit an academic assessment.",
  },
  {
    code: "OK",
    name: "Oklahoma",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "OR",
    name: "Oregon",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "PA",
    name: "Pennsylvania",
    hoursPerYear: 900,
    subjectsRequired: [
      "math",
      "reading",
      "writing",
      "science",
      "history",
      "geography",
      "art",
      "music",
      "physical-education",
    ],
    portfolioRequired: true,
    testingRequired: true,
    notificationOfIntent: true,
    notes:
      "File an annual affidavit, maintain a portfolio, and submit it for evaluation each year. Grades K–6 require 900 hours/year; grades 7–12 require 990 hours/year. Standardized tests required at grades 3, 5, and 8.",
  },
  {
    code: "RI",
    name: "Rhode Island",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "SC",
    name: "South Carolina",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "SD",
    name: "South Dakota",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "TN",
    name: "Tennessee",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "TX",
    name: "Texas",
    hoursPerYear: null,
    subjectsRequired: ["math", "reading", "writing", "science"],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes:
      "Three-subject minimum: reading, spelling/grammar, math, and a course in good citizenship. No notice required.",
  },
  {
    code: "UT",
    name: "Utah",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "VA",
    name: "Virginia",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "VT",
    name: "Vermont",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "WA",
    name: "Washington",
    hoursPerYear: 1000,
    subjectsRequired: [
      "math",
      "reading",
      "writing",
      "science",
      "history",
      "geography",
      "art",
      "music",
      "physical-education",
      "life-skills",
    ],
    portfolioRequired: false,
    testingRequired: true,
    notificationOfIntent: true,
    notes:
      "File a declaration of intent annually; cover the 11 statutory subjects; annual assessment.",
  },
  {
    code: "WI",
    name: "Wisconsin",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "WV",
    name: "West Virginia",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
  {
    code: "WY",
    name: "Wyoming",
    hoursPerYear: null,
    subjectsRequired: [],
    portfolioRequired: false,
    testingRequired: false,
    notificationOfIntent: false,
    notes: STUB_NOTE,
  },
];

// Reference SUBJECTS so the import is retained and downstream tooling can
// verify that the strings used above are members of the canonical subject set.
void SUBJECTS;

const STATE_REQUIREMENT_INDEX: Record<string, StateRequirement> =
  STATE_REQUIREMENTS.reduce<Record<string, StateRequirement>>((acc, req) => {
    acc[req.code.toUpperCase()] = req;
    return acc;
  }, {});

export function getStateRequirement(
  code: string,
): StateRequirement | undefined {
  if (!code) return undefined;
  return STATE_REQUIREMENT_INDEX[code.toUpperCase()];
}
